export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCT_FAILURE';

export const FETCH_SINGLE_PRODUCTS_REQUEST = 'FETCH_SINGLE_PRODUCTS_REQUEST';
export const FETCH_SINGLE_PRODUCTS_SUCCESS = 'FETCH_SINGLE_PRODUCTS_SUCCESS';
export const FETCH_SINGLE_PRODUCTS_FAILURE = 'FETCH_SINGLE_PRODUCTS_FAILURE';
export const SET_TOTAL_PRODUCTS = 'SET_TOTAL_PRODUCTS';
export const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES';