export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCT_FAILURE';

export const FETCH_SINGLE_PRODUCTS_REQUEST = 'FETCH_SINGLE_PRODUCTS_REQUEST';
export const FETCH_SINGLE_PRODUCTS_SUCCESS = 'FETCH_SINGLE_PRODUCTS_SUCCESS';
export const FETCH_SINGLE_PRODUCTS_FAILURE = 'FETCH_SINGLE_PRODUCTS_FAILURE';
export const SET_TOTAL_PRODUCTS = 'SET_TOTAL_PRODUCTS';
export const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES';

export const FETCH_CART_DETAIL_REQUEST = 'FETCH_CART_DETAIL_REQUEST';
export const FETCH_CART_DETAIL_SUCCESS = 'FETCH_CART_DETAIL_SUCCESS';
export const FETCH_CART_DETAIL_FAILURE = 'FETCH_CART_DETAIL_FAILURE';

export const ADD_TO_CART_ITEM_REQUEST = 'ADD_TO_CART_ITEM_REQUEST';
export const ADD_TO_CART_ITEM_SUCCESS = 'ADD_TO_CART_ITEM_SUCCESS';
export const ADD_TO_CART_ITEM_FAILURE = 'ADD_TO_CART_ITEM_FAILURE';

export const REMOVE_CART_ITEM_REQUEST = 'REMOVE_CART_ITEM_REQUEST';
export const REMOVE_CART_ITEM_SUCCESS = 'REMOVE_CART_ITEM_SUCCESS';
export const REMOVE_CART_ITEM_FAILURE = 'REMOVE_CART_ITEM_FAILURE';
export const RESET_REMOVE_CART_ITEM = 'RESET_REMOVE_CART_ITEM'

export const UPDATE_CART_QUANTITY_REQUEST = 'UPDATE_CART_QUANTITY_REQUEST';
export const UPDATE_CART_QUANTITY_SUCCESS = 'UPDATE_CART_QUANTITY_SUCCESS';
export const UPDATE_CART_QUANTITY_FAILURE = 'UPDATE_CART_QUANTITY_FAILURE';
export const RESET_UPDATE_QUANTITY = 'RESET_UPDATE_QUANTITY'
